### ISSUE TITLE
Multitask is not working

### ISSUE THREAD

**Issue by Creator** [Creator/OmniOS#1]
Multitask, is not working.

**Comment by TheOnlyCreator** [comment]
Sorry, I am working on it. Don't be such a bully!

**Comment by TheOnlyCreator** [comment]
I am not a bully, you are one.

**Comment by TheOnlyCreator** [comment]
Closing the issue!

**Comment by Creator** [comment]
![photo3](https://cloud.githubusercontent.com/assets/11231710/6947588/f707f618-d8b0-11e4-8f72-6793218f88d9.jpg)

**Comment by Creator** [comment]
Multitasking works!

**Comment by Creator** [comment]
![yay](https://cloud.githubusercontent.com/assets/11231710/7544999/ce4da41a-f5da-11e4-8104-051f10286c9f.jpg)

**Comment by CrazedProgrammer** [comment]
What the actual fuck Creator? Are you talking to yourself?

**Comment by Creator** [comment]
Man, calm down. I was just in that laughing mood and I felt it would be funny.

**Comment by CrazedProgrammer** [comment]
Okay.
I just thought it looked a bit unprofessional talking to yourself.
If you want to laugh hard you should look up failarmy on YouTube.

**Comment by Creator** [comment]
I regularly watch failarmy, actually.
