### ISSUE TITLE
FTB inventions config

### ISSUE THREAD

**Issue by Coralaris** [Creator/OmniOS#6]
ComputerCraft's config file must be edited to allow OmniOS to be installed correctly on FTB inventions.

I:computerSpaceLimit=1000000
must be changed to at least:
I:computerSpaceLimit=1300000

This is not an issue with your code, this is an issue with a modpack's configuration and I am notifying other users to be aware of this. However, you could avoid this by using an obfuscation script for actual releases. (The main point of obfuscation is compacting files by shortening names in code, it's really just a side effect that it makes code more difficult to modify.) To allow users to develop with your code you can also release both the obfuscation script and developer releases that are not obfuscated. This wouldn't necessarily be a priority for you to do, but the earlier you do it the easier it will be to implement.

**Comment by Creator** [comment]
I know. I haven't developed OmniOS in a long time, so I guess my first task will be to shrink the code. Thanks for the heads up though.
